language: objective-c

osx_image: xcode8.2

script:
- xcodebuild -project MealPlan.xcodeproj -scheme MealPlan -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.1' clean build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
