language: objective-c

osx_image: xcode8.3

script:
- carthage bootstrap --platform iOS
- xcodebuild -project MealPlan.xcodeproj -scheme MealPlan -destination 'platform=iOS Simulator,OS=10.3, name=iPhone 7' clean build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
